### ISSUE TITLE
[QM] ServiceProviderService contains empty path annotation

### ISSUE THREAD

**Issue by berezovskyi** [oslc-op/refimpl#15]
WARNING: The following warnings have been detected: WARNING: The (sub)resource method getServiceProviders in co.oslc.refimpl.qm.gen.services.ServiceProviderService contains empty path annotation.

**Comment by jadelkhoury** [comment]
Yes. it's because the @Path has no "". But not sure why it is a problem.

**Comment by berezovskyi** [comment]
Closing as wontfix for now
